# Server conf
SERVER_HOST = '127.0.0.1'
SERVER_PORT = 8888
CLIENT_REQUEST_TIMEOUT = 60
COMMAND_EXEC_TIMEOUT = 10
REQUEST_END = '\r\n\r\n'
READ_BLOCK_SIZE = 100

# Control server conf
CONTROL_SERVER_HOST = 'vragi-vezde.to.digital'
CONTROL_SERVER_PORT = 51624

# DB conf
MONGO_CONNECTION_URI = 'mongodb://localhost:27017'
MONGO_CONNECTION_MS_TIMEOUT = 15000
MONGO_DB_NAME = 'phone_numbers'

